from .prompts import (
    TITLE_GENERATION_PROMPT,
    HEADLINE_GENERATION_PROMPT,
    BODY_GENERATION_PROMPT,
)

__all__ = [
    'TITLE_GENERATION_PROMPT',
    'HEADLINE_GENERATION_PROMPT',
    'BODY_GENERATION_PROMPT',
]